### ISSUE TITLE
Permission denied errors accessing access_log and error_log

### ISSUE THREAD

**Issue by claym** [linuxserver/docker-muximux#12]
[linuxserverurl]: https://linuxserver.io
[![linuxserver.io](https://raw.githubusercontent.com/linuxserver/docker-templates/master/linuxserver.io/img/linuxserver_medium.png)][linuxserverurl]
	

Ubuntu 17.10
using NFS to mount config directory

```
nginx: [emerg] open() "/config/log/nginx/access.log" failed (13: Permission denied)
[02-Nov-2017 23:34:37] ERROR: failed to open error_log (/config/log/php/error.log): Permission denied (13)
[02-Nov-2017 23:34:37] ERROR: failed to post process the configuration
[02-Nov-2017 23:34:37] ERROR: FPM initialization failed
nginx: [emerg] open() "/config/log/nginx/access.log" failed (13: Permission denied)
[02-Nov-2017 23:34:38] ERROR: failed to open error_log (/config/log/php/error.log): Permission denied (13)
[02-Nov-2017 23:34:38] ERROR: failed to post process the configuration
[02-Nov-2017 23:34:38] ERROR: FPM initialization failed
nginx: [emerg] open() "/config/log/nginx/access.log" failed (13: Permission denied)
[02-Nov-2017 23:34:39] ERROR: failed to open error_log (/config/log/php/error.log): Permission denied (13)
[02-Nov-2017 23:34:39] ERROR: failed to post process the configuration
[02-Nov-2017 23:34:39] ERROR: FPM initialization failed
nginx: [emerg] open() "/config/log/nginx/access.log" failed (13: Permission denied)
[02-Nov-2017 23:34:40] ERROR: failed to open error_log (/config/log/php/error.log): Permission denied (13)
[02-Nov-2017 23:34:40] ERROR: failed to post process the configuration
[02-Nov-2017 23:34:40] ERROR: FPM initialization failed
nginx: [emerg] open() "/config/log/nginx/access.log" failed (13: Permission denied)
[02-Nov-2017 23:34:41] ERROR: failed to open error_log (/config/log/php/error.log): Permission denied (13)
[02-Nov-2017 23:34:41] ERROR: failed to post process the configuration
^C[02-Nov-2017 23:34:41] ERROR: FPM initialization failed
```

So this gets spammed endlessly. If I access the file from the container's command line, I can open the file.

```
root@9f7b50b62166:/config/log/php$ ls -al
total 9
drwxrwxr-x 2 abc abc    4 Nov  3 09:06 .
drwxrwxr-x 4 abc abc    4 Oct 30 21:45 ..
-rw-rw-r-- 1 abc abc    0 Nov  3 09:06 access_log
-rwxrwxr-x 1 abc abc 2346 Nov  1 22:23 error.log
root@9f7b50b62166:/config/log/php$ cat access_log
root@9f7b50b62166:/config/log/php$ cd ../nginx/
root@9f7b50b62166:/config/log/nginx$ cat access.log
```

My docker-compose definition

```
    muximux:
        image: linuxserver/muximux:latest
        container_name: muximux
        volumes:
            - ${DATA}/config/muximux:/config
            - /etc/localtime:/etc/localtime:ro
        env_file: uidgid.env
        environment:
            - VIRTUAL_HOST=muximux.${HOSTNAME}
        restart: always
```
Processes:

```
    1 root       0:00 s6-svscan -t0 /var/run/s6/services
   33 root       0:00 s6-supervise s6-fdholderd
  250 root       0:00 s6-supervise cron
  251 root       0:00 s6-supervise php-fpm
  253 root       0:00 s6-supervise nginx
  255 root       0:00 /usr/sbin/crond -f -S -l 5 -c /etc/crontabs
  310 root       0:00 bash
  596 root       0:00 ps aux
```
Any ideas?
